#!/bin/bash
git add . #komanda "uzmanāmo" mapju pievienošanai
git config --global user.name f4io
git config --global user.email arturs-pauls.kenins@edu.rtu.lv
git commit -m "Class_04b"
git push origin main
